### ISSUE TITLE
winestreamproxy-install fails with 'xxxx:err:sc:wmain failed to create service 87'

### ISSUE THREAD

**Issue by orowith2os** [openglfreak/winestreamproxy#2]
I am using the WINE binaries that XIVLauncher provides, and setting WINEPREFIX to the wineprefix directory in .xlcore.
Am using **WINEPREFIX=~/.xlcore/wineprefix WINE=./wine64 winestreamproxy-install** to install, while in the wine directory that XIVlauncher provides. 
The command fails with *0134:err:sc:wmain failed to create service 87* with the first 4 numbers changing depending on how I set some env vars, such as with /home/user instead of ~

**Comment by openglfreak** [comment]
Hello, please use a Wine build that includes commit wine-mirror/wine@2259cc34a8624a892b02270593bda94b796b72fb.
